#! /bin/sh
### BEGIN INIT INFO
# Provides: noip
# Required-Start: $syslog
# Required-Stop: $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: noip server
# Description:
### END INIT INFO
 
case "$1" in
    start)
        # Starte Programm
        /usr/local/bin/start-pientertain
        ;;
    stop)
        # Beende Programm
        /usr/local/bin/stop-pientertain
        ;;
    *)
        echo "usage /etc/init.d/pientertain {start|stop}"
        exit 1
        ;;
esac
 
exit 0
